# Generated by Django 5.2.6 on 2025-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='citizen',
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, choices=[('municipality', 'Municipality'), ('panchayat', 'Panchayat'), ('pwd', 'PWD'), ('kwa', 'KWA')], max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='google_maps_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
