# Generated by Django 5.2.6 on 2025-09-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_complaint_citizen_alter_officer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officer',
            name='registration_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
