# Generated by Django 5.2.7 on 2025-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_officer_is_verified_officer_registration_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='phone',
        ),
        migrations.AddField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Pending', max_length=20),
        ),
    ]
